# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- id: win
  env:
  - CGO_ENABLED=0
  goos:
  - windows
- id: lnx
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
- id: osx
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  goarch:
  - amd64
- id: fbsd
  env:
  - CGO_ENABLED=0
  goos:
  - freebsd
  goarch:
  - 386
  - amd64
archives:
-
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}{{.Arch}}"
  builds:
    - win
    - osx
    - fbsd
  files:
    - gossiped.example.yml
    - gossiped.tpl
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: osx
    linux: lnx
    windows: win
    freebsd: fbsd
    386: 32
    amd64: 64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Version}}-snapshot"
changelog:
  skip: true
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: gossiped
    package_name: gossiped
    homepage: https://github.com/askovpen/gossiped
    maintainer: askovpen <spam-from-github@skovpen.org>
    license: MIT
    file_name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}{{.Arch}}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: osx
      linux: lnx
      windows: win
      386: 32
      amd64: 64
    formats:
    - deb
    - rpm
    bindir: /usr/bin
    vendor: askovpen
    contents:
      - src: gossiped.example.yml
        dst: /etc/ftn/gossiped.example.yml
        type: config
      - src: gossiped.tpl
        dst: /etc/ftn/gossiped.tpl
        type: config

