language: go

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

go:
- 1.18

addons:
  apt:
    packages:
    - rpm

env:
- GO111MODULE=on

script:
- go build
- ./gossiped
- go test ./... -v -cover -coverprofile=coverage.txt --bench=. -benchmem

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
