# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: linux

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout
      with:
        fetch-depth: 0
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Build
      run: go build 
    - name: Run
      run: ./gossiped
    - name: Test
      run: go test -v ./... -cover -coverprofile=coverage.txt --bench=. -benchmem
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
